version: '3.8'

volumes:
  mysql_taco_001:
    driver: local

services:
  mysql-keycloak:
    image: mysql:8.0.30-oracle
    volumes:
      - mysql_taco_001:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: DB1
      MYSQL_USER: meadmin
      MYSQL_PASSWORD: badpass
    ports:
      - "3310:3306"
