###
POST http://localhost:8080/v1/ingredients/add
Content-Type: application/json

{
  "id": "_TST",
  "name": "Test",
  "type": "WRAP"
}
###

PUT http://localhost:8080/v1/ingredients/_TST
Content-Type: application/json

{
"id": "_TST",
"name": "TestMod",
"type": "SAUCE"
}