POST http://localhost:8082/v1/tacos/add
Content-Type: application/json

{
  "name": "TestTaco",
  "tacoOrderId": "1",
  "ingredients": [
    {
      "id": "SLSA",
      "name": "Salsa",
      "type": "SAUCE"
    },
    {
      "id": "SRCR",
      "name": "Sour Cream",
      "type": "SAUCE"
    }
  ]
}

###

PUT http://localhost:8082/v1/tacos/update
Content-Type: application/json

{
  "id": "5",
  "tacoOrderId": "1",
  "createdAt": "2022-06-28T13:14:09.000+00:00",
  "name": "TestTaco#",
  "ingredients": [
    {
      "id": "SLSA",
      "name": "Salsa",
      "type": "SAUCE"
    },
    {
      "id": "SRCR",
      "name": "Sour Cream",
      "type": "SAUCE"
    },
    {
      "id": "TMTO",
      "name": "Diced Tomatoes",
      "type": "VEGGIES"
    }
  ]
}

###
DELETE http://localhost:8082/v1/tacos/5